1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [9]:
import numpy as np
original_list=list(map(float,input("enter the elements to the list : ").split(" ")))
print(f"original list : {original_list}")
arr = np.array(original_list,ndmin=1)
print(f"one dimention numpy array : {arr}")
print(f"no of dimentions{arr.ndim}")

original list : [10.22, 100.0, 12.22, 324.0]
one dimention numpy array : [ 10.22 100.    12.22 324.  ]
no of dimentions1


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [10]:
import numpy as np
matrix = np.arange(2,11).reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


    3.Write a Python program to create a null vector of size 10 and update sixth value to 11.
    [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
    Update sixth value to 11
    [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [19]:
import numpy as np

vector =np.zeros(10)
print(vector)
vector[6]=11
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [23]:
import numpy as np 
original_list = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]
print("original array: ")
arr = np.array(original_list)
print(arr)
arr = arr[::-1]
print("reverse array")
print(arr)


original array: 
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reverse array
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [28]:
import numpy as np 
matrix =np.ones((5, 5))
print("original list")
print(matrix)
matrix[1:-1,1:-1]=0
print("1 on the border and 0 inside in the array")
print(matrix)

original list
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [30]:
import numpy as np 
matrix = np.ones((3,3))
print("original array")
print(matrix)
matrix = np.pad(matrix,pad_width=1,mode="constant",constant_values=0)
print("0 on the border and 1 inside in the array")
print(matrix)


original array
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [32]:
import numpy as np 
matrix = np.zeros((8,8), dtype=int)
matrix[1::2, ::2] = 1 
matrix[::2, 1::2] = 1  
print("checkerboard pattern : ")
print(matrix)

checkerboard pattern : 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [34]:
import numpy as np 
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
my_list= np.array(my_list)
print("list to array : ")
print(my_list)

my_tuple = ((8,4,6), (1,2,3))
my_tuple=np.array(my_tuple)
print("tuple to array :")
print(my_tuple)

list to array : 
[1 2 3 4 5 6 7 8]
tuple to array :
[[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [40]:
import numpy as np 
arr=np.array([10,20,30])
print("original list")
print(arr)
app=np.array([40,50,60,70,80,90])
arr = np.append(arr, app)
print("\nafter apped values to the end of the array")
print(arr)

original list
[10 20 30]

after apped values to the end of the array
[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [45]:
import numpy as np
arr = np.array([1.0 + 0.j, 0.70710678 + 0.70710678j])
print("original array:")
print(arr)
real_part = np.real(arr)
print("real part of the array:")
print(real_part)
imaginary_part = np.imag(arr)
print("imaginary part of the array:")
print(imaginary_part)


original array:
[1.        +0.j         0.70710678+0.70710678j]
real part of the array:
[1.         0.70710678]
imaginary part of the array:
[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [46]:
import numpy as np
arr = np.array([10, 20, 30])
size = arr.size
print("size of the array:", size)
item_size = arr.itemsize
print("length of one array element in bytes:", item_size)
total_bytes = arr.nbytes
print("total bytes consumed by the elements of the array:", total_bytes)


size of the array: 3
length of one array element in bytes: 4
total bytes consumed by the elements of the array: 12


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [ ]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("array1:", array1)
array2 = np.array([10, 30, 40])
print("array2:", array2)
common_values = np.intersect1d(array1, array2)
print("common values between two arrays:")
print(common_values)


Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays:
[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [53]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("array1:", array1)
array2 = np.array([10, 30, 40, 50, 70, 90])
print("array2:", array2)
set_difference = np.setdiff1d(array1, array2)
print("set difference between two arrays:", set_difference)


array1: [ 0 10 20 40 60 80]
array2: [10 30 40 50 70 90]
set difference between two arrays: [ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [52]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("array1:", array1)
array2 = np.array([10, 30, 40, 50, 70])
print("array2:", array2)
set_xor = np.setxor1d(array1, array2)
print("unique values that are in only one (not both) of the input arrays:", set_xor)


array1: [ 0 10 20 40 60 80]
array2: [10 30 40 50 70]
unique values that are in only one (not both) of the input arrays: [ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [55]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a:", a)
print("Array b:", b)
print("a > b", a > b)
print("a >= b", a >= b)
print("a < b", a < b)
print("a <= b", a <= b)


Array a: [1 2]
Array b: [4 5]
a > b [False False]
a >= b [False False]
a < b [ True  True]
a <= b [ True  True]


15. Write a Python program to save a NumPy array to a text file.

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.savetxt("array.txt", arr, fmt="%d")
print("NumPy array saved to 'array.txt' successfully.")


NumPy array saved to 'array.txt' successfully.


16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [57]:
import numpy as np
array = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:")
print(array)
flattened_array = array.flatten()  
print("New flattened array:")
print(flattened_array)


Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [62]:
import numpy as np
arr = np.array([[2, 4, 6], [6, 8, 10]])
print("original array:")
print(arr)
print("data type of the array x is:", arr.dtype)
arr_float = arr.astype(np.float64)
print("new Type:", arr_float.dtype)
print(arr_float)


original array:
[[ 2  4  6]
 [ 6  8 10]]
data type of the array x is: int32
new Type: float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [64]:
import numpy as np
matrix = np.eye(3,3)
print(matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [72]:
import numpy as np
result = np.tril(np.ones((4, 3)), k=-1)
print(result)


[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: [[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [74]:
import numpy as np

arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])

result = np.concatenate((arr1, arr2), axis=1)
print(result)


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only

In [77]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.flags.writeable = False

print("test the array is read-only or not:")
try:
    arr[0] = 10
except ValueError as e:
    print("error:", e)


test the array is read-only or not:
error: assignment destination is read-only


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]

In [79]:
import numpy as np
arr = np.arange(0,12).reshape(3, 4)

print("original array elements:")
print(arr)
new_arr = arr * 3
print("new array elements:")
print(new_arr)


original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
new array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [80]:
import numpy as np
arr = np.array([[0, 1], [2, 3], [4, 5]])
print("original array elements:")
print(arr)
list_structure = arr.tolist()
print("array to list:")
print(list_structure)


original array elements:
[[0 1]
 [2 3]
 [4 5]]
array to list:
[[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:

Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [85]:
import numpy as np
arr = np.random.rand(10)
print("original array elements:")
print(arr)
list_structure = arr.tolist()
rounded_list = []
for num in list_structure:
    rounded_list.append(round(num, 3))
print("print array values with precision 3:")
print(rounded_list)


original array elements:
[0.95359193 0.37806482 0.93869416 0.38099801 0.70860366 0.62705388
 0.86541509 0.71962152 0.6416284  0.52849403]
print array values with precision 3:
[0.954, 0.378, 0.939, 0.381, 0.709, 0.627, 0.865, 0.72, 0.642, 0.528]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]

In [90]:
import numpy as np
arr = np.array([1.6e-10, 1.6, 1.2e3, 2.35e-1])
np.set_printoptions(suppress=False)  # Reset to default scientific notation
print("Original array elements:")
print(arr)
np.set_printoptions(suppress=True, precision=3)
print("\nPrint array values with precision 3:")
print(arr)


Original array elements:
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]

Print array values with precision 3:
[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]

In [ ]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60]])
new_column = np.array([[100], [200]])  # Column with two rows
result = np.concatenate((arr, new_column), axis=1)
print(result)


[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]

In [93]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("original array:")
print(arr)
indices_to_remove = [0, 3, 4]
new_arr = np.delete(arr, indices_to_remove)
print("delete first, fourth and fifth elements:")
print(new_arr)


original array:
[ 10  20  30  40  50  60  70  80  90 100]
delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]
